language: node_js

node_js:
- "8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
        key_url: 'https://packages.microsoft.com/keys/microsoft.asc'

script:
  - cd Extension
  - npm install
  - npm run pretest
  - npm run test

after_failure:
  - ./.travis/printLogs.sh

after_success:
  - ./.travis/printLogs.sh
  