name: $(Date:yyyMMddd).$(Rev:.r)
pr: 
- 'master'
jobs:
- template: Extension/jobs/build.yml 
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS-10.13'

- template: Extension/jobs/build.yml
  parameters:
    name: Linux
    pool:
      vmImage: 'ubuntu-16.04'

- template: Extension/jobs/build.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'